### ISSUE TITLE
Call service error?

### ISSUE THREAD

**Issue by Nyctobello** [AlexxIT/Jura#15]
Hello,
Was using your add on with my Z8 without issues until this morning where the following error (bottom of screenshot) came about. On RPi4 HAOS - latest OS and HA updates (24.1, i believe) 

A
![IMG_3857](https://github.com/AlexxIT/Jura/assets/125308849/1adbb0b6-c29b-4805-a71e-40f353d0c5ec)
ny ideas?

**Comment by iwansanders** [comment]
same problem here with Jura S8

**Comment by Avatar1976** [comment]
Something changed in 24.1 guys this is the same issue I posted about those numeric entities are disabled in the device.
Still broken in 24.1.1 too so from a HA core perspective I suspect it may be expected. 😓

**Comment by Nyctobello** [comment]
The same thing in 24.1.2 FYI

**Comment by AlexxIT** [comment]
#14

**Comment by Nyctobello** [comment]
Thanks @AlexxIT ! Your fix worked! :) if so inclined, you can add Z8 as a device with which  your addon is fully compatible.
