### ISSUE TITLE
no macadress

### ISSUE THREAD

**Issue by remb0** [AlexxIT/Jura#2]
put 3 different dongles in my nuc  but none of them finds a macadres..
is it possible that esphome also picks up the jura?

**Comment by AlexxIT** [comment]
Show device diagnostics for Bluetooth integration

**Comment by remb0** [comment]
![image](https://github.com/AlexxIT/Jura/assets/649642/75c76ef2-b743-4743-be93-bf01feea8ff6)
`dmesg | grep Bluetooth
uetooth: hci0: command 0x1001 tx timeout
[   10.568322] Bluetooth: hci1: Bootloader revision 0.3 build 0 week 24 2017
[   10.569185] Bluetooth: hci1: Device revision is 1
[   10.569190] Bluetooth: hci1: Secure boot is enabled
[   10.569192] Bluetooth: hci1: OTP lock is enabled
[   10.569195] Bluetooth: hci1: API lock is enabled
[   10.569196] Bluetooth: hci1: Debug lock is disabled
[   10.569198] Bluetooth: hci1: Minimum firmware build 1 week 10 2014
[   10.569498] Bluetooth: hci1: Found device firmware: intel/ibt-20-1-3.sfi
[   10.569589] Bluetooth: hci1: Boot Address: 0x24800
[   10.569592] Bluetooth: hci1: Firmware Version: 255-255.255
[   10.570170] Bluetooth: hci1: unexpected event for opcode 0x0000
[   10.576140] Bluetooth: hci1: unexpected event for opcode 0x0000
[   10.578210] Bluetooth: hci1: Failed to send firmware signature (-38)
[   10.581501] Bluetooth: hci1: Intel reset sent to retry FW download
[   15.519445] Bluetooth: hci0: RTL: HCI_OP_READ_LOCAL_VERSION failed (-110)
[   25.510216] Bluetooth: hci1: Bootloader revision 0.3 build 0 week 24 2017
[   25.511251] Bluetooth: hci1: Device revision is 1
[   25.511256] Bluetooth: hci1: Secure boot is enabled
[   25.511258] Bluetooth: hci1: OTP lock is enabled
[   25.511260] Bluetooth: hci1: API lock is enabled
[   25.511262] Bluetooth: hci1: Debug lock is disabled
[   25.511264] Bluetooth: hci1: Minimum firmware build 1 week 10 2014
[   25.511527] Bluetooth: hci1: Found device firmware: intel/ibt-20-1-3.sfi
[   25.511612] Bluetooth: hci1: Boot Address: 0x24800
[   25.511614] Bluetooth: hci1: Firmware Version: 255-255.255
[   27.913248] Bluetooth: hci1: Waiting for firmware download to complete
[   27.913254] Bluetooth: hci1: Firmware loaded in 2367576 usecs
[   27.913345] Bluetooth: hci1: Waiting for device to boot
[   27.928366] Bluetooth: hci1: Device booted in 14836 usecs
[   27.932371] Bluetooth: hci1: Found Intel DDC parameters: intel/ibt-20-1-3.ddc
[   27.934215] Bluetooth: hci1: Applying Intel DDC parameters completed
[   27.935132] Bluetooth: hci1: Firmware revision 0.3 build 144 week 11 2023
[   28.000608] Bluetooth: MGMT ver 1.22
[   51.957371] Bluetooth: RFCOMM TTY layer initialized
[   51.957383] Bluetooth: RFCOMM socket layer initialized
[   51.957391] Bluetooth: RFCOMM ver 1.11
➜  ~ `

my esphomes working also as bluetooth receivers for my plantsensors.

**Comment by AlexxIT** [comment]
No. Enter both your devices and click download diagnostics

**Comment by remb0** [comment]
oops sorry.
[config_entry-bluetooth-68a5204bbac68da2ffcc870624ba01ec.json.txt](https://github.com/AlexxIT/Jura/files/12706352/config_entry-bluetooth-68a5204bbac68da2ffcc870624ba01ec.json.txt)
[config_entry-bluetooth-3a969f9b3853f58017561d08817a4be3.json.txt](https://github.com/AlexxIT/Jura/files/12706353/config_entry-bluetooth-3a969f9b3853f58017561d08817a4be3.json.txt)

**Comment by AlexxIT** [comment]
Do you know mac address of your Jura? What's your model?
I can't see it in device diagnostics.

**Comment by remb0** [comment]
Jura E8 but just found out that I have the whiti wifi module instead of bluetooth :(

**Comment by AlexxIT** [comment]
Can you turn on your Jura remotely via WiFi? Because I can't do it via Bluetooth.

**Comment by remb0** [comment]
No not possible because the adapter got no power.  but I bought a switchbot/fingerbot for it.
