### ISSUE TITLE
working with an s8

### ISSUE THREAD

**Issue by phillip199310** [AlexxIT/Jura#20]
confirmed working with an s8

**Comment by AlexxIT** [comment]
Thanks

**Comment by EwoudDG** [comment]
Confirmation from here to, very great job Alexx! Very happy with this integration.

BUT!, it did not work without more, I to was hanging on mac ok, but no devices tó with my PI4 and build-in BT. Almost bought a very expensive Bluetooth dongle, until I stumbled upon another [thread](https://github.com/AlexxIT/Jura/issues/9), which suggested to completely power down the PI and reboot. Re-integrate BT, re-integrate Jura and pronto; HA can brew coffee!
