### ISSUE TITLE
Jura J8 twin w/ ESP32 wroom proxy

### ISSUE THREAD

**Issue by marceld83** [AlexxIT/Jura#27]
Hi! 

Love the work you did! I used to have an old F70, equipped with a ESPhome solution to ensure my fresh coffee as soon as I wake up. 

Nowadays, I got lucky buying an brand new J8 Twin. Following all instructions with help of an ESP32 Wroom It recognizes a mac adress, but after selecting it I get an unnamed device without any devices or entities. 

Is this normal, given the age of the machine, or should I try again? And is there any way I can contribute?

Please let me know
Best, Marcel

**Comment by AlexxIT** [comment]
Show screens how this looks like. Also provide integration/device diagnostics for Bluetooth integration.

**Comment by marceld83** [comment]
Hi Alex. 

Of course. here you go:

Bluetooth integration doesn't work, I am using a proxy:
![image](https://github.com/user-attachments/assets/c3c3fb5e-3af5-4b38-9806-970b58c0c0c3)


When I add my Jura:
![image](https://github.com/user-attachments/assets/52677408-81ac-458e-9fec-16b7b9f51a1d)

After I added my Jura:
![image](https://github.com/user-attachments/assets/d4e0aafb-d3c2-4295-b9af-8d646744fdd6)


Logfile does come up with an error:

[JuraLog.txt](https://github.com/user-attachments/files/16903183/JuraLog.txt)

2024-09-06 07:05:35.726 ERROR (MainThread) [homeassistant.components.bluetooth.manager] Error in bluetooth callback
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 109, in _discover_service_info
callback(service_info, BluetoothChange.ADVERTISEMENT)
File "/config/custom_components/jura/__init__.py", line 23, in update_ble
devices[entry.entry_id] = Device(
^^^^^^^
File "/config/custom_components/jura/core/device.py", line 52, in __init__
machine = get_machine(number)
^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/jura/core/device.py", line 207, in get_machine
with f.open("machinefiles/" + items[2] + ".xml") as xml:
^^^^^
UnboundLocalError: cannot access local variable 'items' where it is not associated with a value

2024-09-06 07:05:39.926 ERROR (MainThread) [homeassistant.components.bluetooth.manager] Error in bluetooth callback
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 109, in _discover_service_info
callback(service_info, BluetoothChange.ADVERTISEMENT)
File "/config/custom_components/jura/__init__.py", line 23, in update_ble
devices[entry.entry_id] = Device(
^^^^^^^
File "/config/custom_components/jura/core/device.py", line 52, in __init__
machine = get_machine(number)
^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/jura/core/device.py", line 207, in get_machine
with f.open("machinefiles/" + items[2] + ".xml") as xml:
^^^^^
UnboundLocalError: cannot access local variable 'items' where it is not associated with a value

**Comment by marceld83** [comment]
Thank you for you vivid response. If there's anything else, or the information is incomplete, please let me know!

**Comment by AlexxIT** [comment]
> Also provide integration/device diagnostics for Bluetooth integration.

https://www.home-assistant.io/integrations/bluetooth/
https://www.home-assistant.io/integrations/diagnostics/

**Comment by marceld83** [comment]
Hi Alex,

Thanks again for your quick reaction. I will try to look into these
integrations next weekend. Cheers!

Op vr 6 sep 2024 09:48 schreef Alex X ***@***.***>:

**Comment by AlexxIT** [comment]
You already have Bluetooth integration. You just needs to download diagnostics from GUI.

**Comment by marceld83** [comment]
You sure? When i try to install bluetooth integration it provides an error
message:

[image: image.png]

I cannot find the bluetooth integration in the list. I did find the
diagnostics button for another integration. I thought i wouldn't get an BT
integration because of the ESP32 bluetooth proxy I installed?



Op vr 6 sep 2024 om 16:42 schreef Alex X ***@***.***>:

**Comment by AlexxIT** [comment]
No, I'm not sure. But you getting error from bluetooth integration... So I don't know where you should get it's diagnostics.
Without this info it's hard to help you.

**Comment by marceld83** [comment]
I understand, I have a bluetooth dongle lying around, and will try to set
that up. Thanks for your support so far!

Op vr 6 sep 2024 19:46 schreef Alex X ***@***.***>:

**Comment by marceld83** [comment]
Hi Alex,

Took me a while, but I got the bluetooth dongle setup and working. Please
find the diagnostics report attached. It does indeed find a TT214H BlueFrog
(starting from line 556). The result is the same, images as sent earlier.


I sure hope you can help me get further, if there's anything I can do to
help, please let me know.

best, Marcel

Op za 7 sep 2024 om 09:21 schreef Marcel van Dijk ***@***.***>:

**Comment by AlexxIT** [comment]
You have not attached anything.

**Comment by marceld83** [comment]
I checked, it's there. I'll attach it again. Better luck this time?

Op di 10 sep 2024 19:43 schreef Alex X ***@***.***>:

**Comment by AlexxIT** [comment]
No

**Comment by marceld83** [comment]
A reply through GitHub this time, sorry for the inconvenience. 


[config_entry-bluetooth-01J7DJY82N1MK6W0XJ37AD5HQX.json](https://github.com/user-attachments/files/16950313/config_entry-bluetooth-01J7DJY82N1MK6W0XJ37AD5HQX.json)

**Comment by AlexxIT** [comment]
I can't see Jura in your diagnostics. You needs to add it via new bluetooth. And than get diagnostics.

**Comment by marceld83** [comment]
Hi Alex! Hope you're doing well. I'm not giving up yet, installed HA on a RPI with bluetooth support. Got it quite close to my Jura, tried to connect with same result. However, I think the diagnostics do contain Jura (TT214H Bluefrog) information. Can you take another look? 

Thanks!

[config_entry-bluetooth-01JB4D6MR38DTYRM3NJ9RA8MWG.json](https://github.com/user-attachments/files/17600701/config_entry-bluetooth-01JB4D6MR38DTYRM3NJ9RA8MWG.json)

**Comment by AlexxIT** [comment]
Looks like you have super new model. I have updated supported models list. You can check latest master version.

**Comment by marceld83** [comment]
Thank you very much. The update did the trick. I now can confirm that a wroom ESP32 development board with ESPHome bluetooth proxy also works like a charm, as well as the Jura J8 twin. 

Awesome!
