### ISSUE TITLE
Working setup with Jura ENA8 and ESPHome bluetooth proxy

### ISSUE THREAD

**Issue by PipoCanaja** [AlexxIT/Jura#3]
Hi @AlexxIT 

This issue is just to let you know that your component is installed successfully here : 
- Jura ENA8 (the 'old' one, with bluetooth dongle and no touchscreen
- ESPHome Bluetooth Proxy
  - [M5Stack ATOM Lite](http://docs.m5stack.com/en/core/atom_lite)
- I had to disable the PIN to succeed

I have no idea if the PIN logic was reverse engineered, just started to look at connecting my coffee machine a few hours ago :) But if at any time you start something on the PIN, ping me :) 

I have never wrote a single line of code for HA and never played with python. I am more like a C, perl guy, but I will try to understand your code !

<img width="792" alt="image" src="https://github.com/AlexxIT/Jura/assets/38363551/f9c7ae76-85ac-4344-95fe-d5cfe337c182">

Bye and thanx for sharing it!

**Comment by AlexxIT** [comment]
I haven't studied how PIN logic works. Just disabled it for simplicity.
Maybe I'll look into it in the future. But I can't promise anything. I have a huge number of projects.
