### ISSUE TITLE
Integration Install fails

### ISSUE THREAD

**Issue by Krzysztonek** [AlexxIT/Jura#30]
When trying to install this integration, I'm getting the below screen:
![obraz](https://github.com/user-attachments/assets/f89543d7-f05a-465d-b2f4-324add0903b4)
with no possibility to edit/add MAC address. I'm stuck at this stage.

Moreover, when trying to install Bluetooth integration, I'm getting the below message:
![obraz](https://github.com/user-attachments/assets/c7716e58-116f-4337-999a-3a172ef0d2da)

**Comment by AlexxIT** [comment]
You need to look for answers in the HA community. You have a problem with Bluetooth integration.
Until it works - this component will not be able to connect to your coffee maker.
