### ISSUE TITLE
Is there support for ena4?

### ISSUE THREAD

**Issue by muratozk** [AlexxIT/Jura#32]
I have an Ena4 device. I am trying to use the data of these other models. However, I was not successful. I wonder if it uses a different data set. Also, can we test it simply from the serial interface?

**Comment by AlexxIT** [comment]
If you can control it via Jura mobile app via bluetooth - your model should be supported.

**Comment by AlexxIT** [comment]
This integration only about original bluetooth module. I have no idea how serial interface works for this devices.

**Comment by muratozk** [comment]
I tested it again with the USB to TTL converter along with the level shifter and I could not receive any data from the device. I felt the need to respond so that anyone else would have information if they searched. thank you @AlexxIT

**Comment by AlexxIT** [comment]
Check useful links section from readme
