### ISSUE TITLE
E8 Showing as unavailable or disconnected.

### ISSUE THREAD

**Issue by nsleigh** [AlexxIT/Jura#8]
First off thanks to releasing this, it has been something I wanted to integrate for sometime.

I have connected my E8 (it showed in the integration as soon as I added it) but in the diagnostics it shows as disconnected and if I restart the integration it changes to unavailable. I am connecting via an ASUS USB-BT500 which I think is a supported device and it is about 3m from the machine.

Any ideas what to try to resolve this?

**Comment by AlexxIT** [comment]
Disconnected by default is OK. Integration does not connect to the device if it is not necessary.

**Comment by nsleigh** [comment]
Ok, it now shows as unavailable. If I re-add it to get to Disconnected, I can see the Product options but everything else shows as unavailable.

**Comment by nsleigh** [comment]
My bad, I was misunderstanding how it worked. Once I selected the product I could see the options!
