### ISSUE TITLE
When adding coffee machine no device or entities created

### ISSUE THREAD

**Issue by Avatar1976** [AlexxIT/Jura#9]
My Giga5 with Bluetooth adapter is detected (Mac address appears and adds to home assistant with out errors) ok but after adding I have no entities or devices. 
Thanks for your efforts so far was pleased to see someone working on an integration for our beloved Jura coffee machines. 😊
Is it possible the Giga 5 just isn't supported yet?
![Screenshot_20231228_065648_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/6a7ff997-4a8e-4930-bb23-97c7b75199d9)

**Comment by AlexxIT** [comment]
Setup integration is only first step when your BT can see device with right name:
https://github.com/AlexxIT/Jura/blob/7aa7ef9338860b5366a777ef5bf9753a02d6c631/custom_components/jura/config_flow.py#L14

Second step is your device should send info with model number and your BT adapter should support active connection mode:
https://github.com/AlexxIT/Jura/blob/7aa7ef9338860b5366a777ef5bf9753a02d6c631/custom_components/jura/__init__.py#L36

**Comment by Avatar1976** [comment]
> 
> Second step is your device should send info with model number and your BT adapter should support active connection mode:
> 

Are you suggesting I need to change HA Bluetooth adapters? Is their log files anywhere I can assist troubleshooting with providing?

**Comment by Avatar1976** [comment]
I did find this setting in my Raspberry Pi 4 Bluetooth adapter settings just now (what I run my HA installation from).
![Screenshot_20231228_072641_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/cdabd1e0-22a2-4136-8743-168f2440565c)
Is this part of the issue potentially? Do I need to disable this?

**Comment by AlexxIT** [comment]
Sometimes you just needs to wait. If you not using some BT proxy - your BT should support connection mode. And you will get problems with "bad" adapter only during control step.

**Comment by Avatar1976** [comment]
So the workflow seems to look like this (going to say something is not right with its comms with the coffee machine).
![Screenshot_20231228_073320_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/1afe6b72-d74c-4e1b-bb73-51acc4c8b813)
![Screenshot_20231228_073346_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/689bdc6f-b9d8-471d-8490-5dd68bc1e3e8)

**Comment by Avatar1976** [comment]
Disabled aforementioned passive scanning mode on my Bluetooth config in HA and it errors on loop (initialising, then erroring as per below). 
![Screenshot_20231228_074047_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/a1cc1b6d-d029-4e2c-8bb2-aa468ec0fcae)
So likely to be the built in raspberry pi4 Bluetooth adapter not suitable for use with your integration?

**Comment by Avatar1976** [comment]
https://github.com/home-assistant/core/issues/98461
Looks to be an ongoing issue with rp4 (and potentially also rp3). Hard reset of my rp4 (full power down) and restarting without passive setting appears to have now allowed me to add my Giga5 as expected.
![Screenshot_20231228_081339_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/d28e0a17-3f7f-48a7-8408-ac3f0040b0a6)

Do get intermittent connection drops though but other than that seems to work as expected:
![Screenshot_20231228_080337_Home Assistant](https://github.com/AlexxIT/Jura/assets/47725430/0e039106-e8ac-4b1a-9e52-d1a747e25f60)
